### ISSUE TITLE
mango::image::jpeg::HuffmanTable::decode uses BMI instruction set when disabled in CMake

### ISSUE THREAD

**Issue by tomysshadow** [t0rakka/mango#19]
It's me again. Based on the discussion we had in #11 I decided for my application to target SSE4. Recently, I made my first public release and immediately I had someone [report a crash.](https://github.com/tomysshadow/M4Revolution/issues/1) After looking at the crash dump, I determined that it was coming from `mango::image::jpeg::HuffmanTable::decode`. Further investigation revealed it was the `buffer.peekBits` function, which ultimately calls `u64_extract_bits` from bits.hpp.

Both `__BMI__` and `MANGO_CPU_64BIT` macros are defined in the x64 build, so it uses the BMI enabled version. But I had BMI unchecked when I built the solution in CMake. The only options I had enabled were `ENABLE_SSE2`, `ENABLE_SSE4`, and also `ENABLE_NEON` because it's on by default (but that shouldn't impact x64.) It is also unclear to me from looking at the source how the `-mbmi` compiler option set in the CMake project is meant to have an impact on the macro definition, as it seems `__BMI__` is always defined for x64 on Visual Studio 2019 or newer.

I was using mango 1.3.0 but the issue still appears to be present currently.

**Comment by t0rakka** [comment]
OK, seems just build configuration issue.. I'll take a look at the cmake configs.

**Comment by t0rakka** [comment]
_bextr_u64 is valid with BMI, so the question is when we don't wan't BMI.. digging..

**Comment by t0rakka** [comment]
It's me.. I am the criminal..

    #if defined(MANGO_CPU_INTEL) && defined(MANGO_CPU_64BIT) && (_MSC_VER >= 1920)

        #ifndef __BMI__
        #define __BMI__
        #endif

I think we want to move some of these into options and call it a day.. looking at details..

**Comment by t0rakka** [comment]
Here's the current meson side:

# Intel ISA Extensions
option('enable_bmi',          type : 'boolean', value : false, description : 'Enable BMI'   )
option('enable_bmi2',         type : 'boolean', value : false, description : 'Enable BMI2'  )
option('enable_sha',          type : 'boolean', value : true,  description : 'Enable SHA'   )
option('enable_f16c',         type : 'boolean', value : true,  description : 'Enable F16C'  )
option('enable_fma',          type : 'boolean', value : false, description : 'Enable FMA'   )

**Comment by t0rakka** [comment]
I might be better off switching SHA and F16C also off, then get them with the deluxe script that I wrote for myself  ;----)

**Comment by t0rakka** [comment]
I see what's going on..

OPTION(ENABLE_BMI           "Enable BMI"                                OFF)
OPTION(ENABLE_BMI2          "Enable BMI2"                               OFF)
OPTION(ENABLE_FMA           "Enable FMA"                                OFF)

-->

            target_compile_options(mango PUBLIC "-mbmi")
            target_compile_options(mango PUBLIC "-mlzcnt")

vs2019 doesn't have compiler flags for these; the compiler "just can do it" after specific version but seems only when specifically told with intrinsic, so seeing no other "convenient way" I just switch them on.. need a compiler definition of our own for msvc. I'll add a few bits and these CMake OPTIONs should start taking effect. I re-use __BMI__ but it will come from cmake instead of configure.hpp, that should do it.

**Comment by t0rakka** [comment]
Check out "options" branch, upgraded both CMake and meson for more options. The CMake options that don't have compiler flag for msvc are passed to configure.hpp as compiler defs. Not tested yet but publishing early on the branch.

Headers still are on their own.. they have to pick up the configuration from where ever it comes..

**Comment by tomysshadow** [comment]
Appears to work - builds, and Visual Studio shows the non-BMI implementation highlighted now. I plan on uploading a test build for the user to try to confirm it is no longer crashing for them

**Comment by t0rakka** [comment]
I'll refactor and clean up still; the MANGO_MSVC_ macros are not needed; I can use same macros gcc/clang use and make everything simpler. The NOSIMD "mode" also toggles some ISA extensions off which is unacceptable in hindsight but I'll try to keep the spirit that ISA extensions like BMI are opt-in.

**Comment by t0rakka** [comment]
Pushed the clean up for meson + cmake; if you can confirm it's OK on your use can merge.

**Comment by tomysshadow** [comment]
User reports that everything is working now
