### ISSUE TITLE
please example unity :(

### ISSUE THREAD

**Issue by PlayMeron** [t0rakka/mango#37]
please example unity :(

**Comment by t0rakka** [comment]
Unity as in Unity 3D, the game engine? I haven't really thought about making any add-ons for it at this time. I been working on Blender based export-import 3D asset pipeline (for my own uses) and it's coming along pretty nicely.. but I think Unity already has fantastic tools for this kind of stuff so my interests don't align that well.. 

If I misunderstood your request, sorry. Feel free to give me additional details what you are looking for / interested in / suggesting.

**Comment by PlayMeron** [comment]
unity 3d, only supports loading of images in the main thread, and produces lag and screen freezing for heavy images, I planned to use a lib of images, to solve this.

**Comment by t0rakka** [comment]
Ah, that makes sense.. I think they are mostly C# these days and would need some kind of integration going. Honestly I have no idea where to begin with that as I haven't worked with unity 3d before. My older image loading library was used in some really ancient versions of unity (2003 and before) but I think they switched to Freeimage (could be wrong, haven't followed) and no clue what they are using now. I'm out of my depth when it comes to unity programming.. you could say compeltely useless.. hehe.. =)

**Comment by t0rakka** [comment]
I am not familiar with unity plugin authoring so unable to help with that, sorry.
