### ISSUE TITLE
capture layered window

### ISSUE THREAD

**Issue by xixihao123** [t0rakka/mango#39]
![image](https://user-images.githubusercontent.com/45343237/63583767-384cc180-c5ce-11e9-9597-fc26fa48882c.png)
Hi,Hello I have a Windows GDI problem, How can I capture layered windows with GDI？I cross-process capture a window of HWND, and then I want to save it bitmap, window is translucent style when why save without pixels?

**Comment by t0rakka** [comment]
I would prefer library related problems / issues. That said, I am currently on macOS & Linux so can't test this but here's something that might help:

https://docs.microsoft.com/en-us/windows/win32/gdi/capturing-an-image

After you have a pointer to the data you can set up mango::Surface to describe what you have and continue from there.
