### ISSUE TITLE
encode char

### ISSUE THREAD

**Issue by w136111526** [t0rakka/mango#48]
Hello, I want to use mango conversion GBK and UTF8 why not corresponding method

**Comment by t0rakka** [comment]
You need to use some library or other code to do it; the mango is only concerned about file formats it supports. The current code is for dealing with filenames in ZIP and RAR files; they need to be convertible to UTF8 as it is the universal format most other systems can (or should) deal with. The idea is that if I have a filename in, say, RAR file it must be "printable" to either console or custom glyph renderer. That's it.. the idea is not to be a complete Babylon cross conversion library.
