### ISSUE TITLE
cannot initialize a variable of type 'void *' with an rvalue of type 'FARPROC' (aka 'long long (*)()')

### ISSUE THREAD

**Issue by tksuoran** [t0rakka/mango#6]
Trying to build my fork of mango in msys2 clang64 environment using clang 18.1.8 gives this error:
```
mango/source/mango/core/win32/dynamic_library.cpp:38:19: error: cannot initialize a variable of type 'void *' with an rvalue of type 'FARPROC' (aka 'long long (*)()')
   38 |             void* ptr = ::GetProcAddress(handle, symbol.c_str());
      |                   ^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
The code looks same in here in "proper" mango repo.

**Comment by t0rakka** [comment]
I don't have MSYS2 or windows close by (vacation) just macOS laptop, so I'll try reinterpret_cast magic and commit it, let me know if it worked.. =/ If it doesn't, you have the environment; propose a fix instead.. let's get this compiling again! =P

For now, let me know if the fix worked. :)

**Comment by t0rakka** [comment]
Installed MSYS2, fixed every issue I could find with clang-18 and gcc-13+14 so closing this with some extra fixes thrown in as bonus.
