### ISSUE TITLE
jpg decode from ConstMemory never calls parser or creates header -> fails to decode

### ISSUE THREAD

**Issue by diablodale** [t0rakka/mango#69]
Hi. I'm on my first try with mango and I never see jpg bytes being decoded. Using the MSVC debugger, I never see a call into the parser which populates the header and decodes.

I'm using code related to https://github.com/t0rakka/mango/issues/27 and your mango example `image_loading.cpp`.

### Setup

* VS 2019 Community 16.6.5
* Mango ec099ef3ec214992986be057668e87d855c7f24e

### Repro

1. Use code similar to the following

```
static const auto theFormat{mango::FORMAT_B8G8R8A8};
mango::ConstMemory mangoMem(colorJpgRawDataBuffer, colorJpgByteSize);
mango::ImageDecoder decoder(mangoMem, ".jpg");
if (decoder.isDecoder()) {
    auto header {decoder.header()};
    std::cout << "found " << header.width << "x" << header.height << std::endl;
    mango::Surface surface(
        output.pixelcols,
        output.pixelrows,
        theFormat,
        (int)output.stride,
        output.dataBuffer);
    auto result = decoder.decode(surface);
    std::cout << "result " << result.success << " and " << result.info << std::endl;
}
```

2. Compile
3. Inspect the `output.dataBuffer` and the debug text on stdout

### Result

The dataBuffer has no decompressed image data. The header has 0 width and height. The result is 0 and no info.

### Expected

Decompressed image data in the dataBuffer

### Notes

To my knowledge and the tracing I did, given the code above, mango never parses and never creates a header. Therefore, when `m_interface->decode()` is called and it reaches `ImageDecodeStatus Parser::decode(Surface& target)` on line 1754 of `jpeg_decode.cpp`, the `if (!scan_memory.address || !header)` will fail because nothing has populated the header and scan_memory. Therefore, the decode will fail.

**Comment by t0rakka** [comment]
I tested with following changes and the image decoded:

    mango::filesystem::File file("test.jpg");
    mango::ConstMemory mangoMem = file;//(colorJpgRawDataBuffer, colorJpgByteSize);

The two first bytes of the colorJpgRawDataBuffer should be 0xff, 0xd8 ; can you verify these are correct? The last bytes should be 0xff, 0xd9 which is the jpeg end-of-image marker.

**Comment by t0rakka** [comment]
The parse() is protected by isJPEG() check, which is essentially:

        if (!memory.address || memory.size < 4)
            return false;

        if (uload16be(memory.address) != MARKER_SOI)
            return false;

First we check for nullptr, and second that we have at least 4 bytes in the file. The interesting bit is the Start Of Image marker check.. that's why the most likely cause for failure is that the 0xff,0xd8 SOI marker is missing from beginning of the address you pass to the decoder.

Let's say you might have some extra header/magic before the actual file begins depending on how you obtained the address. I could see some container format adding some magic header bits before the image file in certain situations.. if you can determine that, oh, I need to skip 6 bytes and subtract 6 from the size or similar effect to make it work.

Not saying we can't have bug on this side either but the current master branch seems to work OK as tested above. Status at this time is "can't reproduce" :(

**Comment by t0rakka** [comment]
The missing SOI marker is now correctly indicated in the header.info so that the cause of failure is more clear to the caller.

**Comment by diablodale** [comment]
*I can* see a successful decompression by Mango. My databuffer now has MJPG with `FFD8` and last two are `FFD9`.

I made a mistake in my test harness.  Found it when I checked for the `FFD8` start. A sideaffect of another code change was sending NV12 data.  And I found the `isJPEG()`...I missed it as the constructor within the constructor for the `Interface`. 🤦‍♂️ Sorry about that. 

I'm seeing better utilization of all my CPU cores, and total time to decompress is about 65% that of libjpeg-turbo.
Nice work :-)

I found two very minor build harness improvements. I'll send them as a PR later today.

I have an question unrelated to this issue. How can I read your debug print output to investigate *if* my MJPG datastream has restart markers and that Mango is spinning up multiple threads to do work *if* possible? Is it the debug output of `Restart interval: 1005`?

I did a highlevel read of jpeg_decode.cpp. Is it `decodeSequentialMT()` that does this? I don't see any debug output of `Process: [%d, %d] --> ThreadPool`. To check further, I added a debugPrint() in the `else` clause within `decodeSequentialMT()` at line 2105 and that debug output *does* appear within an [SOS] section. I've included that debug output below.

<details>
<summary>debug print output</summary>

```
[ SOI ]
  Time: 32 us

[ DQT ]
  Quantization table #0 element precision: 8 bits
  Quantization table #1 element precision: 8 bits
  Quantization table #2 element precision: 8 bits
  Time: 34 us

[ SOF0 ]
  Image: 1920 x 1080 x 8
  Encoding: Baseline DCT
  Compression: Huffman
  Frame: 0, compid: 1, Hsf: 2, Vsf: 1, Tq: 0, offset: 0
  Frame: 1, compid: 2, Hsf: 1, Vsf: 1, Tq: 1, offset: 2
  Frame: 2, compid: 3, Hsf: 1, Vsf: 1, Tq: 2, offset: 3
  Blocks per MCU: 4
  MCU size: 16 x 8
  16200 MCUs (120 x 135) -> (1920 x 1080)
  Image: 1920 x 1080
  Clip: 0 x 0
  Time: 50 us

  Decoder: SSE2 YCbCr 16x8
[ DHT ]
  Huffman table #0 table class: 0
    codes: 0 1 5 1 1 1 1 1 1 0 0 0 0 0 0 0 
  Time: 51 us

[ DHT ]
  Huffman table #0 table class: 1
    codes: 0 2 1 3 3 2 4 3 5 5 4 4 0 0 1 125 
  Time: 38 us

[ DHT ]
  Huffman table #1 table class: 0
    codes: 0 3 1 1 1 1 1 1 1 1 1 0 0 0 0 0 
  Time: 70 us

[ DHT ]
  Huffman table #1 table class: 1
    codes: 0 2 1 2 4 4 3 4 7 5 4 4 0 1 2 119 
  Time: 39 us

[ COM ]
  Time: 2 us

[ APP0 ]
  Time: 3 us

[ DRI ]
  Restart interval: 1005  <-------------------------------------------
  Time: 4 us

[ SOS ]
  components: 3
  Component: 1, DC: 0, AC: 0, offset: 0, size: 2
      - offset: 0, pred: 0,
      - offset: 64, pred: 0,
  Component: 2, DC: 1, AC: 1, offset: 2, size: 1
      - offset: 128, pred: 1,
  Component: 3, DC: 1, AC: 1, offset: 3, size: 1
      - offset: 192, pred: 2,
  Spectral range: (0, 63)
  Process with restart interval   <--------------------------------------------
  Time: 6501 us

[ EOI ]
  Time: 5 us
```

</details>

**Comment by t0rakka** [comment]
The debug prints are a but clumsy and only for my internal "tuning sessions" ; you need to uncomment the ENABLE macro in jpeg.hpp .. it's a bit sad how it "works" .. I didn't think it would be useful for anything else. =) 

In a long-term I am trying to figure out how to leverage in-hardware JPEG engines in Intel CPU's, mobile chipsets and such but the API landscape how to access the hardware is a worse mess than my code so it might take a while.

Another aspiration is that when the decoding target is hardware surface like OpenGL or DirectX, I could use compute for part of the workload. At minimum for the YCbCr to RGB(A) conversion. It would be trivial thing to do as far as coding is concerned, but more tricky to configure.. you would have to link with this and that 3D API on case basis. 

I also benchmarked against Apple's internal HW decoder engine. The HW engine is super fast but doesn't decode all files and becomes super slow if need to read back the decoded buffer. GPU memory to system memory readback kills the performance and it becomes much slower than the code we have here. Its optimized to reading a file and consuming the data within the GPU. It's kind of the same thing I was planning above.

Just some directions this might go in the future..  FYI: thanks for the PR!

**Comment by t0rakka** [comment]
Regarding thee RST marker issue, I could add it into the decode result info. All mango written files have restart internal, it uses them to multi-thread the encoding as well.

**Comment by t0rakka** [comment]
Done; the decode info string will have "[RST]" at the end if the file had restart markers.

**Comment by diablodale** [comment]
On windows, I've read that intel, amd, and nvidia all expose their HW decoders within Windows Media Foundation. If your destination surface is DirectX, then that might be a single API approach for them all. If DirectX isn't your surface, then you'll need to do the typical copyback to CPU memory.

Otherwise, it is like you write...each of the vendors has their own proprietary API, libraries, etc. I'm experimenting with Intel's Media SDK next week.
