### ISSUE TITLE
image\jpeg project throws exception

### ISSUE THREAD

**Issue by zapcity** [t0rakka/mango#72]
I was only able to get mango\example\image\jpeg\jpeg.cpp working once I placed `Path path(getPath(folder));` at line 41, i.e.

```
size_t input_bytes = 0;
size_t image_bytes = 0;
Path path(getPath(folder));
if (mmap)
{
```

I think there might be some issue with calling `path.pathname()`. It seems to be returning "foo/bar/pic.jpg" instead of "foo/bar/".

Great project btw! I've been looking for the fastest jpeg decoder around. Mango decoding seems very fast. Will have to test against libjpeg-turbo. Thanks!

**Comment by t0rakka** [comment]
The first argument has to be a folder such as foo/ not a jpeg filename foo/bar.jpg, if you give it a filename instead of folder it won't see any files since a jpeg file isn't a folder. ;)

I'd rather keep it the way it is, as it is example it should demo the best practises, although it's never completely wrong to patch wrong input. Maybe check if the initial parameter is a file or folder and return appropriate error message to the user?

I'll see if I at on this one and will close the issue when I make a decision, cool?

**Comment by t0rakka** [comment]
Clarification:  the path.pathname() doesn't do any parsing or anything like that, it just returns the parameter the path was initialised with. It's a convenience member function.

If a path is sub-pathed: 
`Path a("foo/"); Path b(a, "bar/");`

Then the pathname() will return the combined path "foo/bar/", which is stored in the m_pathname member variable; all the parsing and juggling is done at the constructor.

So if it returned a jpeg filename, then my initial guess is that you gave a filename as the folder argument to the program. :)

**Comment by t0rakka** [comment]
It's pretty cool that you found a work-around / fix to the issue but it just fixed the incorrect input.. cleaner fix would have the first line in test_jpeg() to do it, so replace that line with yours and it should also have the same effect.

**Comment by zapcity** [comment]
Thanks, it's all works fine now. I've been using Windows 10 VS2019 to compile this. I initially tried variants like the following (where jpegs are in the same directory as image.exe):

- image . 
- image E:\dev\projects\mango\image\x64\Debug

But they didn't work. Once I appended a backslash to the pathname:

- image .\
- image E:\dev\projects\mango\image\x64\Debug\

it's all working fine now. I should have looked more into the functionality of `Path path(folder)` :) Thanks so much again for this work of yours!

**Comment by t0rakka** [comment]
Yeah, the backslash is mandatory since files can be "folders" in this system:

data.zip is a file
data.zip/ is a folder

:D

Also: thanks!
