### ISSUE TITLE
Does it support image scaling while decoding?

### ISSUE THREAD

**Issue by infrontofme** [t0rakka/mango#75]
Resize image

**Comment by t0rakka** [comment]
There used to be scaling routines years ago ( < 2010 ) but those were removed. 

When the data is consumed by a GPU it is recommended that the images are stored in atlas when a lot of smaller images are used. GPUs support NPOT2 textures quite well these days so there is very little reason to pre-scale. There are some corner cases where you might want to stretch the image with CPU and store the resampled image but those are rare.

For display purposes it's more efficient to leave the scaling to the GPU; you an do bilinear/bicubic scaling quite easily. If you feel that it is wasteful to do it per frame, you can render the scaled output into FBO and use that as source texture but if the filter is bilinear or nearest, it makes very little sense especially if you are enlarging the image it will just take more storage for no other benefit. Bicubic requires  a custom shader so in theory you save a little bit of power but I wouldn't be too excited about that unless the GPU is really slow and you are doing something like rendering UI at 4K.

I recommend GPU scaling if possible. If you insist on CPU scaling I recommend writing one for 32 bit RGBA and forgetting other formats (unless your target format is a specific one, then knock yourself out).
