### ISSUE TITLE
pkware zip 6.3.9 

### ISSUE THREAD

**Issue by kyoto44** [t0rakka/mango#90]
Hello, can you update your zip implementation to pkware's 6.3.9?
It brings support of zstd compression in .zip format.

**Comment by t0rakka** [comment]
That's a cool idea, didn't know they still updated their container.. we have zstd built-in, I hope it's just calling the right codec.. I'l take a look at it. =)

**Comment by t0rakka** [comment]
Help me a bit; I purchased a license for Windows command line and GUI winzip, but their version is 14.xx and has no option to make zstd archive. I made PPMD and LZMA test files so will check those out. I also tested with latest 7z and it did not have zstd compression for zip container either.

If you can provide a test file I can use it to add support and test, or instructions how to make a test file. I did not find 6.3.9 from pkware themselves, their version number is 14.xx as mentioned earlier.

Their support site had the latest appnotes and zstd is listed on supported compression formats.

**Comment by t0rakka** [comment]
Ah, 6.3.9 refers to the file format specification version.. TLDR: 7z and pkzipc 14.latest don't seem to have support yet. :_(

**Comment by kyoto44** [comment]
> Ah, 6.3.9 refers to the file format specification version.. TLDR: 7z and pkzipc 14.latest don't seem to have support yet. :_(
https://github.com/mcmilk/7-Zip-zstd it supports zstd in zip

**Comment by t0rakka** [comment]
Done.. seems to work. :)

`        File file(pathname + info.name);
        u32 checksum = crc32(0, file);
        printf("checksum: 0x%8x\n", checksum);
`

**Comment by t0rakka** [comment]
The compression wrapper code is identical for BZIP2, ZSTD and LZMA. I clean that up a bit..

**Comment by t0rakka** [comment]
Now that I look at old code, the error reporting could also use a bit of cleaning up. I already use the error-status object in ImageEncoder / Decoder interface, similar thing might be nice here when user wants easier access to what went wrong. I don't want to litter small API changes in small doses, probably overhaul of the whole thing happens eventually for MANGO9000 or something.

I like exceptions in higher level code, but for low-level code they are just annoying - but - still want to get something better than just error code.. ignore this, just "thinking aloud" :P

**Comment by t0rakka** [comment]
Cleaning code done, turned out quite sweet. =P
